spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/postgres
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver



  jpa:
    hibernate:
      ddlAuto: none
    properties:
      hibernate.default_schema: thing
    openInView: false


  sql:
    init:
      mode: never
  liquibase:
    changeLog: classpath:/db.changelog\changelog-master.xml
    liquibaseSchema: thing
